version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    logging:
      driver: none
  app:
    build: .
    container_name: app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/server
